Ext.define('dlmsprint2a.model.Filters', {
    extend : 'Ext.data.Model',
    fields : [
        { name : "name" },        
        { name : "description" },
        { name : "exportfile" },        
        { name : "count" },        
        { name : "exported" },        
        { name : "modified" },        
        { name : "exporttpl" },
        { name : "enable" },
        { name : "monday" },
        { name : "tuesday" },
        { name : "wednesday" },
        { name : "thursday" },
        { name : "friday" },
        { name : "saturday" },
        { name : "sunday" },
        { name : "time" },
    ],
});
